apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-timeapi-deployment
  namespace: time-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-timeapi
  template:
    metadata:
      labels:
        app: my-timeapi
    spec:
      containers:
        - name: my-timeapi-container
          image: akaehomen321/time-api-app:v1.0.2
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"      # Request 1/10th of a CPU core
              memory: "128Mi"  # Request 128 Mebibytes of RAM
            limits:
              cpu: "250m"      # Limit to 1/4th of a CPU core
              memory: "256Mi"  # Limit to 256 Mebibytes of RAM  
          readinessProbe:
            httpGet:
              path: / # The endpoint to check. Root endpoint is perfect for this.
              port: 8000
            initialDelaySeconds: 50 # Wait 15s after startup before first check. Gives app time to connect to DB.
            periodSeconds: 10     # Check every 10 seconds.
            timeoutSeconds: 2     # Wait max 5s for a response.
            failureThreshold: 3   # Consider it failed after 3 consecutive failures.
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60 # Wait longer for the liveness probe to give it more time to recover.
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret 
                  key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: my-timeapi-service
  namespace: time-api-app
spec:
  selector:
    app: my-timeapi
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort