apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: time-api-app
# This deployment will manage the PostgreSQL database for the FastAPI application.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"      # Request 1/10th of a CPU core
              memory: "256Mi"  # Request 128 Mebibytes of RAM
            limits:
              cpu: "500m"      # Limit to 1/4th of a CPU core
              memory: "512Mi"  # Limit to 256 Mebibytes of RAM
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data # name for this volume inside the pod
          persistentVolumeClaim:
            claimName: postgres-pvc # name of the PVC created in postgres-pvc.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: time-api-app
# This service will expose the PostgreSQL database to other pods in the same namespace.
# It allows the FastAPI application to connect to the database using a stable endpoint.
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432