# .github/workflows/build-and-push.yml

name: Docker Build and Push

# TRIGGER: This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches: [ "main" ]
     # Also trigger the workflow on pushes of tags that look like versions (e.g., v1.0, v1.2.3)
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # LOGIN: Logs into Docker Hub using the secrets you configured.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step is a best practice. It automatically extracts tags and labels
      # from the git ref and other context, making your image tags more meaningful.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: akaehomen321/time-api-app  

      # BUILD & PUSH: Builds the image and pushes it to Docker Hub
      # It uses the tags and labels generated in the previous 'meta' step.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}